# config.yml

publish_mode: editorial_workflow

backend:
  name: github
  repo: tiagoafpereira/tiagoafpereira.github.io
  branch: main
  base_url: https://inductiva-decapcms-oauth.nfshost.com/
  # auth_endpoint: /login/oauth/authorize
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: preview/{{slug}}
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
